# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :wy_sync do
    match(type: "development", force_for_new_devices: false, readonly: true)
  end

  # 推送证书
  lane :wy_pem do
    get_push_certificate(output_path: 'fastlane', p12_password: 'pswd1234', development: true)
    get_push_certificate(output_path: 'fastlane', p12_password: 'pswd1234')
  end
end
